#!/bin/sh
#
# starts process to continuously log temperature-values
#
CLOCKREADER=/sbin/hwclock
SETSYSTEMOPT=-s
SETHARDOPT=-w
OPT4ALL=-u

case "$1" in
        start)
                #$CLOCKREADER $OPT4ALL $SETSYSTEMOPT
                [ -f /temperature.log ] && cp /temperature.log /tmp/
                [ -f /humidity.log ] && cp /humiditiy.log /tmp/
                /usr/local/bin/temp_logger &
                ;;
        stop)
                cp /tmp/temperature.log /
                cp /tmp/humidity.log /
                sync
                ;;
        *)
                echo "Usage: $0 {start|stop}"
                exit 1
                ;;
esac
exit 0

