#!/bin/sh
#
# starts process to continuously log temperature-values
#
CLOCKREADER=/sbin/hwclock
SETSYSTEMOPT=-s
SETHARDOPT=-w
OPT4ALL=-u

case "$1" in
        start)
                #$CLOCKREADER $OPT4ALL $SETSYSTEMOPT
                /usr/local/bin/temp_logger &
                ;;
        stop)
                #$CLOCKREADER $OPT4ALL $SETHARDOPT
                ;;
        *)
                echo "Usage: $0 {start|stop}"
                exit 1
                ;;
esac
exit 0

